#!/usr/bin/env php
<?php

declare(strict_types=1);

$options = getopt('', ['stdout::', 'help::']);

if (array_key_exists('help', $options)) {
    fwrite(STDOUT, <<<TEXT
Usage:
  php .agents/scripts/refresh_memory.php [--stdout]

Options:
  --stdout    Print the generated MEMORY.md content instead of writing the file

TEXT);
    exit(0);
}

$root = dirname(__DIR__, 2);
$knowledgeDir = $root . '/.agents/knowledge';
$memoryPath = $knowledgeDir . '/MEMORY.md';

$knowledgeFiles = [];
$iterator = new RecursiveIteratorIterator(
    new RecursiveDirectoryIterator($knowledgeDir, FilesystemIterator::SKIP_DOTS)
);

foreach ($iterator as $fileInfo) {
    if (! $fileInfo instanceof SplFileInfo || ! $fileInfo->isFile()) {
        continue;
    }

    $path = $fileInfo->getPathname();
    if (! str_ends_with($path, '.md')) {
        continue;
    }

    if (basename($path) === 'MEMORY.md') {
        continue;
    }

    if (str_starts_with($path, $knowledgeDir . '/archive/')) {
        continue;
    }

    $knowledgeFiles[] = $path;
}

sort($knowledgeFiles);

$learningFiles = glob($root . '/.agents/learnings/*.json') ?: [];
$learnings = [];

foreach ($learningFiles as $file) {
    $decoded = json_decode((string) file_get_contents($file), true);
    if (is_array($decoded) && isset($decoded['id'])) {
        $learnings[] = $decoded;
    }
}

$activeLearnings = array_values(array_filter(
    $learnings,
    static fn (array $learning): bool => ($learning['status'] ?? 'captured') !== 'superseded'
));

$scopes = [];
$reviewTargets = 0;

foreach ($activeLearnings as $learning) {
    $scope = (string) ($learning['scope'] ?? 'unknown');
    $scopes[$scope] = true;

    $target = (string) ($learning['promotion_target'] ?? 'none');
    $confidence = (string) ($learning['confidence'] ?? 'low');
    $rule = trim((string) ($learning['candidate_rule'] ?? ''));

    if ($rule !== '' && $target !== 'none' && $confidence !== 'high') {
        $reviewTargets++;
    }
}

$knowledgeRows = [];
$futureRows = [];

foreach ($knowledgeFiles as $file) {
    $contents = (string) file_get_contents($file);
    $summary = extractHeading($contents) ?? basename($file);
    $relativePath = ltrim(str_replace($knowledgeDir . '/', '', $file), '/');
    $knowledgeRows[] = sprintf('| `%s` | %s |', $relativePath, escapePipes($summary));

    if (basename($file) === 'future-considerations.md') {
        $futureRows = extractFutureRows($contents);
    }
}

$date = (new DateTimeImmutable('now'))->format('Y-m-d');
$lines = [
    '# Agent Memory Index',
    '',
    '<!-- Generated by .agents/scripts/refresh_memory.php -->',
    '',
    'このファイルは `.agents/knowledge/` の索引です。',
    '目的は、長い知識を増やすことではなく、「今どこに何があるか」を短時間で把握できるようにすることにあります。',
    '',
    '通常は `php .agents/scripts/refresh_memory.php` で再生成します。',
    '',
    '## Active Knowledge',
    '',
    '| Topic | Summary | Source of Truth | Last Reviewed |',
    '|------|---------|----------------|---------------|',
    sprintf('| `agent-improvement` | 学びの記録、昇格基準、圧縮ルール | `../agent-improvement.md` | %s |', $date),
    '',
    '## Promotion Targets',
    '',
    '| Target | What Belongs Here | Notes |',
    '|-------|-------------------|-------|',
    '| `AGENTS.md` | 全体原則、用語、判断境界 | 事例集を持ち込まない |',
    '| `skills/*/SKILL.md` | 特定作業の短い手順 | 長文化したら `references/` へ移す |',
    '| `skills/*/references/` | 詳細ルール、失敗例、レビュー観点 | スキル本文の補助に限定する |',
    '| `.agents/knowledge/` | 整理済み知識、索引、横断ノート | 人間が読み返すための記憶 |',
    '| `.agents/learnings/` | 生の観察、未昇格メモ | 1ファイル1論点を維持する |',
    '',
    '## Learning Snapshot',
    '',
    sprintf('- Active learnings: %d', count($activeLearnings)),
    sprintf('- Active scopes: %d', count($scopes)),
    sprintf('- Pending review targets: %d', $reviewTargets),
    '',
    '## Knowledge Files',
    '',
    '| File | Summary |',
    '|------|---------|',
];

if ($knowledgeRows === []) {
    $lines[] = '| _None_ | _No knowledge files yet._ |';
} else {
    array_push($lines, ...$knowledgeRows);
}

array_push(
    $lines,
    '',
    '## Future Reminders',
    '',
);

if ($futureRows === []) {
    $lines[] = '- _No future reminders._';
} else {
    array_push($lines, ...$futureRows);
}

array_push(
    $lines,
    '',
    '## Archive Policy',
    '',
    '- 失効した整理済み知識は `archive/` に移す',
    '- アーカイブ理由をファイル冒頭に1行で残す',
    '- 同じ論点で新しい知識を作った場合は、後継ファイルを明記する',
    ''
);

$markdown = implode("\n", $lines);

if (array_key_exists('stdout', $options)) {
    fwrite(STDOUT, $markdown);
    exit(0);
}

$bytes = @file_put_contents($memoryPath, $markdown);

if ($bytes === false) {
    fwrite(STDERR, "Failed to write memory file: {$memoryPath}\n");
    exit(1);
}

fwrite(STDOUT, $memoryPath . PHP_EOL);

function extractHeading(string $contents): ?string
{
    foreach (splitLines($contents) as $line) {
        $trimmed = trim($line);
        if ($trimmed === '' || str_starts_with($trimmed, '<!--')) {
            continue;
        }

        if (str_starts_with($trimmed, '# ')) {
            return trim(substr($trimmed, 2));
        }
    }

    return null;
}

function escapePipes(string $text): string
{
    return str_replace('|', '\|', $text);
}

function extractFutureRows(string $contents): array
{
    $lines = splitLines($contents);
    $rows = [];
    $currentTitle = null;
    $revisitWhen = null;
    $status = null;

    foreach ($lines as $line) {
        $trimmed = trim($line);

        if (str_starts_with($trimmed, '### ')) {
            if ($currentTitle !== null) {
                $rows[] = formatFutureReminder($currentTitle, $status, $revisitWhen);
            }

            $currentTitle = trim(substr($trimmed, 4));
            $revisitWhen = null;
            $status = null;
            continue;
        }

        if (str_starts_with($trimmed, '- Status:')) {
            $status = trim(substr($trimmed, strlen('- Status:')));
            continue;
        }

        if (str_starts_with($trimmed, '- Revisit When:')) {
            $revisitWhen = trim(substr($trimmed, strlen('- Revisit When:')));
        }
    }

    if ($currentTitle !== null) {
        $rows[] = formatFutureReminder($currentTitle, $status, $revisitWhen);
    }

    return $rows;
}

function formatFutureReminder(string $title, ?string $status, ?string $revisitWhen): string
{
    $parts = ['- ' . $title];

    if ($status !== null && $status !== '') {
        $parts[] = "Status: {$status}";
    }

    if ($revisitWhen !== null && $revisitWhen !== '') {
        $parts[] = "Revisit When: {$revisitWhen}";
    }

    return implode(' / ', $parts);
}

function splitLines(string $contents): array
{
    $normalized = str_replace(["\r\n", "\r"], "\n", $contents);

    return explode("\n", $normalized);
}
